version: 0.2

env:
  variables:
    LANG: "ja_JP.UTF-8"
    LANGUAGE: "ja_JP:ja"
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - ls -al
      - apt -y update
      - apt -y install language-pack-ja-base language-pack-ja graphviz fonts-ipafont plantuml
      # 言語設定
      - locale-gen ja_JP.UTF-8
      - /usr/sbin/update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
      - export LANG=ja_JP.UTF-8
      - export LANGUAGE=ja_JP:ja
      # pipenvのインストール
      - pip install --upgrade pip
      - pip install --user pipenv
      - pipenv install --dev
  build:
    commands:
      - ls -al
      - pipenv run sphinx-build -b html source build
artifacts:
  files:
    - "**/*"
  base-directory: "build/"
